version: '3.2'
services:
#----------------------ZOOKEEPER FOR KAFKA--------------------
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    hostname: zookeeper
    expose:
    - "2181"
#----------------------KAFKA SERVICE--------------------------
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "TopicSysLog:1:1"
#----------------------FILEBEAT SERVICE-----------------------
  filebeat:
    image: test:1
    hostname: filebeat_producer
    ports:
      - "2020:2020"
    command: filebeat -e -strict.perms=false
    volumes:
       - "/var/log:/usr/share/filebeat/dockerlogs/data:ro"
       - type: bind
         source: ./filebeat.yml
         target: /usr/share/filebeat/filebeat.yml
    depends_on:
      - kafka
#----------------------METRICBEAT SERVICE---------------------
  metricbeat:
    image: mbeat:1
    hostname: metricbeat
    environment:
      - "WAIT_FOR_HOSTS=elasticsearch:9200 kibana:5601"
      - "HOST_ELASTICSEARCH=elasticsearch:9200"
      - "HOST_KIBANA=kibana:5601"
    command: metricbeat -e -strict.perms=false
    volumes:
      - type: bind
        source: ./metricbeat/metricbeat.yml
        target: /usr/share/metricbeat/metricbeat.yml
        read_only: true
    depends_on:
      - kafka 
      - elasticsearch
#----------------------ELASTICSEARCH SERVICE------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    hostname: elasticsearch
    cap_add:
      - IPC_LOCK
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: ./elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
    ports:
      - "9200:9200"
#----------------------KIBANA SERVICE------------------------
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.2
    hostname: kibana
    volumes:
      - type: bind
        source: ./kibana.yml
        target: /opt/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
#volumes:
#  server_logs:
