metrcibeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
#-------------KAFKA MODULE------------------
- module: kafka
  hosts: ["kafka:9092"]
  period: 1m
  enabled: true
  topics: ["TopicSysLog"]
#-------------OUTPUT CONFIG----------------
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  protocol: https
  path: /elasticsearch
  username: "metricbeat_anonymous_user"
#  password: "mypass"

logging.level: debug
